export const dummyData = [
  {
  id: 1,
  imgUrl: "https://velog.velcdn.com/images/n0eyes/post/de461fbc-bb49-4997-8115-9bd0186a1978/image.png",
  title: "제목입니다",
  desc: "설명입니다",
  series: "테스트시리즈1",
  tags: ["test", "dummy", "data"],
  date: "아마 타임스탬프?",
  comments: ["댓글", "입니다"],
  },
  {
    id: 2,
    imgUrl: null,
    title: "제목입니다",
    desc: "설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다설명입니다",
    series: "테스트시리즈1",
    tags: ["test", "dummy", "data"],
    date: "아마 타임스탬프?",
    comments: ["댓글", "입니다"],
  },
  {
    id: 3,
    imgUrl: "https://velog.velcdn.com/images/n0eyes/post/de461fbc-bb49-4997-8115-9bd0186a1978/image.png",
    title: "제목입니다",
    desc: "설명입니다",
    series: "테스트시리즈2",
    tags: ["test", "dummy", "data"],
    date: "아마 타임스탬프?",
    comments: ["댓글", "입니다"],
    },
    {
      id: 4,
      imgUrl: null,
      title: "제목입니다",
      desc: "설명입니다",
      series: "테스트시리즈2",
      tags: ["test", "dummy", "data"],
      date: "아마 타임스탬프?",
      comments: ["댓글", "입니다"],
    },
    {
      id: 5,
      imgUrl: null,
      title: "제목입니다",
      desc: "설명입니다",
      series: "테스트시리즈2",
      tags: ["test", "dummy", "data"],
      date: "아마 타임스탬프?",
      comments: ["댓글", "입니다"],
    },
]